name: Build MelonLoader
run-name: ${{ vars.DEVVERSION }}${{ github.event_name != 'workflow_dispatch' && format('-ci.{0}', github.run_number) || '' }} | ${{ github.event_name != 'workflow_dispatch' && (github.event.head_commit.message || format('`[PR]` {0}', github.event.pull_request.title)) || 'Manual Build' }}

on:
  push:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  pull_request:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  workflow_dispatch:

jobs:
  build_core:
    name: Build Windows Binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Debug for win-x64
        run: dotnet build --no-restore -c Debug -p:RID="win-x64" -p:Version="${{ vars.DEVVERSION }}${{ github.event_name != 'workflow_dispatch' && format('.{0}', github.run_number) || '' }}"

      - name: Upload Debug for win-x64
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Windows.x64.CI.Debug
          path: Output/Debug/win-x64

      - name: Build Release for win-x64
        run: dotnet build --no-restore -c Release -p:RID="win-x64" -p:Version="${{ vars.DEVVERSION }}${{ github.event_name != 'workflow_dispatch' && format('.{0}', github.run_number) || '' }}"

      - name: Upload Release for win-x64
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.Windows.x64.CI.Release
          path: Output/Release/win-x64

      - name: Pack NuGet Package
        run: dotnet pack --no-build -c Release -p:Version="${{ vars.DEVVERSION }}${{ github.event_name != 'workflow_dispatch' && format('-ci.{0}', github.run_number) || '' }}"

      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MelonLoader.NuGet
          path: Output/Release/win-x64/MelonLoader/LavaGang.MelonLoader.${{ vars.DEVVERSION }}${{ github.event_name != 'workflow_dispatch' && format('-ci.{0}', github.run_number) || '' }}.nupkg