name: Build MelonLoader

# Controls when the action will run. 
on:
  push:
    branches: [ci-test]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build Script
        shell: bash
        run: |
          echo Invoking MSBuild...
          msbuild /t:Rebuild
          echo Done
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Debug Build
          path: ./Output/Debug/MelonLoader/*