name: Build MelonLoader

on:
  push:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  pull_request:
    branches: [ master, alpha-development, v0.6.0-rewrite ]
  workflow_dispatch:

jobs:
  build_core_debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Build Melonloader Core
        shell: cmd
        run: msbuild /restore /p:Platform="Windows - x64" # Platform is actually irrelevant for core, it's compiled as AnyCPU either way
      - name: Upload core artifact
        uses: actions/upload-artifact@v3
        with:
          name: MLCoreDebug
          path: Output/Debug/MelonLoader/
  build_core_release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Build Melonloader Core
        shell: cmd
        run: msbuild /restore /p:Configuration=Release /p:Platform="Windows - x64"
      - name: Upload core artifact
        uses: actions/upload-artifact@v3
        with:
          name: MLCoreRelease
          path: Output/Release/MelonLoader/
  build_rust_x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          # Target triple to install for this toolchain
          target: i686-pc-windows-msvc
      - name: Build Rust | Windows - x86
        shell: cmd
        run: cargo +nightly build --release --toolchain i686-pc-windows-msvc
      - name: Upload proxy x86
        uses: actions/upload-artifact@v3
        with:
          name: MLProxyX86
          path: target/i686-pc-windows-msvc/release/proxy.dll
      - name: Upload bootstrap x86
        uses: actions/upload-artifact@v3
        with:
          name: MLBootstrapX86
          path: target/i686-pc-windows-msvc/release/Bootstrap.dll
          
  build_rust_x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          # Target triple to install for this toolchain
          target: x86_64-pc-windows-msvc
      - name: Build Rust | Windows - x64
        shell: cmd
        run: cargo +nightly build --release --toolchain x86_64-pc-windows-msvc
      - name: Upload proxy x64
        uses: actions/upload-artifact@v3
        with:
          name: MLProxyX64
          path: target/x86_64-pc-windows-msvc/release/proxy.dll
      - name: Upload bootstrap x64
        uses: actions/upload-artifact@v3
        with:
          name: MLBootstrapX64
          path: target/x86_64-pc-windows-msvc/release/Bootstrap.dll
  finalize_x64_debug_zip:
    runs-on: windows-latest
    needs: [build_core_debug, build_rust_x64]
    steps:
      - uses: actions/checkout@v3
      - name: Download core artifact
        uses: actions/download-artifact@v3
        with:
          name: MLCoreDebug
          path: Output/Debug/x64/MelonLoader/
      - name: Download proxy x64
        uses: actions/download-artifact@v3
        with:
          name: MLProxyX64
          path: Output/Debug/x64/
      - name: Download bootstrap x64
        uses: actions/download-artifact@v3
        with:
          name: MLBootstrapX64
          path: Output/Debug/x64/MelonLoader/Dependencies/
      - name: Package x64 zip
        shell: cmd
        run: |
          echo Copying Managed Libs...
          mkdir Output\Debug\x64\MelonLoader\Managed\
          xcopy BaseLibs\Managed Output\Debug\x64\MelonLoader\Managed\ /E /H /Y
          echo.
          echo Copying Mono x64...
          mkdir Output\Debug\x64\MelonLoader\Dependencies\MonoBleedingEdge.x64\
          xcopy BaseLibs\MonoBleedingEdge.x64 Output\Debug\x64\MelonLoader\Dependencies\MonoBleedingEdge.x64\ /E /H /Y
          echo.
          echo Copying documentation files...
          copy NOTICE.txt Output\Debug\x64
          mkdir Output\Debug\x64\MelonLoader\Documentation
          copy CHANGELOG.md Output\Debug\x64\MelonLoader\Documentation\
          copy LICENSE.md Output\Debug\x64\MelonLoader\Documentation\
          copy NOTICE.txt Output\Debug\x64\MelonLoader\Documentation\
          copy README.md Output\Debug\x64\MelonLoader\Documentation\
      - uses: actions/upload-artifact@v3
        name: Upload Zip | Windows - x64
        with:
          name: MelonLoader.x64.CI.Debug
          path: ./Output/Debug/x64/*
  finalize_x86_debug_zip:
    runs-on: windows-latest
    needs: [build_core_debug, build_rust_x86]
    steps:
      - uses: actions/checkout@v3
      - name: Download core artifact
        uses: actions/download-artifact@v3
        with:
          name: MLCoreDebug
          path: Output/Debug/x86/MelonLoader/
      - name: Download proxy x86
        uses: actions/download-artifact@v3
        with:
          name: MLProxyX86
          path: Output/Debug/x86/
      - name: Download bootstrap x86
        uses: actions/download-artifact@v3
        with:
          name: MLBootstrapX86
          path: Output/Debug/x86/MelonLoader/Dependencies/
      - name: Package x86 zip
        shell: cmd
        run: |
          echo Copying Managed Libs...
          mkdir Output\Debug\x86\MelonLoader\Managed\
          xcopy BaseLibs\Managed Output\Debug\x86\MelonLoader\Managed\ /E /H /Y
          echo.
          echo Copying Mono x86...
          mkdir Output\Debug\x86\MelonLoader\Dependencies\MonoBleedingEdge.x86\
          xcopy BaseLibs\MonoBleedingEdge.x86 Output\Debug\x86\MelonLoader\Dependencies\MonoBleedingEdge.x86\ /E /H /Y
          echo.
          echo Copying documentation files...
          copy NOTICE.txt Output\Debug\x86
          mkdir Output\Debug\x86\MelonLoader\Documentation
          copy CHANGELOG.md Output\Debug\x86\MelonLoader\Documentation\
          copy LICENSE.md Output\Debug\x86\MelonLoader\Documentation\
          copy NOTICE.txt Output\Debug\x86\MelonLoader\Documentation\
          copy README.md Output\Debug\x86\MelonLoader\Documentation\
      - uses: actions/upload-artifact@v3
        name: Upload Zip | Windows - x86
        with:
          name: MelonLoader.x86.CI.Debug
          path: ./Output/Debug/x86/*
  finalize_x64_release_zip:
    runs-on: windows-latest
    needs: [build_core_release, build_rust_x64]
    steps:
      - uses: actions/checkout@v3
      - name: Download core artifact
        uses: actions/download-artifact@v3
        with:
          name: MLCoreRelease
          path: Output/Release/x64/MelonLoader/
      - name: Download proxy x64
        uses: actions/download-artifact@v3
        with:
          name: MLProxyX64
          path: Output/Release/x64/
      - name: Download bootstrap x64
        uses: actions/download-artifact@v3
        with:
          name: MLBootstrapX64
          path: Output/Release/x64/MelonLoader/Dependencies/
      - name: Package x64 zip
        shell: cmd
        run: |
          echo Copying Managed Libs...
          mkdir Output\Release\x64\MelonLoader\Managed\
          xcopy BaseLibs\Managed Output\Release\x64\MelonLoader\Managed\ /E /H /Y
          echo.
          echo Copying Mono x64...
          mkdir Output\Release\x64\MelonLoader\Dependencies\MonoBleedingEdge.x64\
          xcopy BaseLibs\MonoBleedingEdge.x64 Output\Release\x64\MelonLoader\Dependencies\MonoBleedingEdge.x64\ /E /H /Y
          echo.
          echo Copying documentation files...
          copy NOTICE.txt Output\Release\x64
          mkdir Output\Release\x64\MelonLoader\Documentation
          copy CHANGELOG.md Output\Release\x64\MelonLoader\Documentation\
          copy LICENSE.md Output\Release\x64\MelonLoader\Documentation\
          copy NOTICE.txt Output\Release\x64\MelonLoader\Documentation\
          copy README.md Output\Release\x64\MelonLoader\Documentation\
      - uses: actions/upload-artifact@v3
        name: Upload Zip | Windows - x64
        with:
          name: MelonLoader.x64.CI.Release
          path: ./Output/Release/x64/*
  finalize_x86_release_zip:
    runs-on: windows-latest
    needs: [build_core_release, build_rust_x86]
    steps:
      - uses: actions/checkout@v3
      - name: Download core artifact
        uses: actions/download-artifact@v3
        with:
          name: MLCoreRelease
          path: Output/Release/x86/MelonLoader/
      - name: Download proxy x86
        uses: actions/download-artifact@v3
        with:
          name: MLProxyX86
          path: Output/Release/x86/
      - name: Download bootstrap x86
        uses: actions/download-artifact@v3
        with:
          name: MLBootstrapX86
          path: Output/Release/x86/MelonLoader/Dependencies/
      - name: Package x86 zip
        shell: cmd
        run: |
          echo Copying Managed Libs...
          mkdir Output\Release\x86\MelonLoader\Managed\
          xcopy BaseLibs\Managed Output\Release\x86\MelonLoader\Managed\ /E /H /Y
          echo.
          echo Copying Mono x86...
          mkdir Output\Release\x86\MelonLoader\Dependencies\MonoBleedingEdge.x86\
          xcopy BaseLibs\MonoBleedingEdge.x86 Output\Release\x86\MelonLoader\Dependencies\MonoBleedingEdge.x86\ /E /H /Y
          echo.
          echo Copying documentation files...
          copy NOTICE.txt Output\Release\x86
          mkdir Output\Release\x86\MelonLoader\Documentation
          copy CHANGELOG.md Output\Release\x86\MelonLoader\Documentation\
          copy LICENSE.md Output\Release\x86\MelonLoader\Documentation\
          copy NOTICE.txt Output\Release\x86\MelonLoader\Documentation\
          copy README.md Output\Release\x86\MelonLoader\Documentation\
      - uses: actions/upload-artifact@v3
        name: Upload Zip | Windows - x86
        with:
          name: MelonLoader.x86.CI.Release
          path: ./Output/Release/x86/*
  cleanup_artifacts:
    runs-on: windows-latest
    needs: [finalize_x86_debug_zip, finalize_x64_debug_zip, finalize_x86_release_zip, finalize_x64_release_zip]
    steps:
      - uses: GeekyEggo/delete-artifact@v2.0.0
        with:
          name: |
            MLCoreDebug
            MLCoreRelease
            MLProxyX86
            MLBootstrapX86
            MLProxyX64
            MLBootstrapX64
